In [ ]:
import numpy as np
my_arr = np.arange(21)
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [ ]:
my_arr[10]

10

In [ ]:
my_arr[5:15]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
my_arr[5:15:5]

array([ 5, 10])

In [ ]:
my_arr[5:16:5]

array([ 5, 10, 15])

In [ ]:
two_dim = np.array([[0,10,20],[5,15,25],[100,200,300]])
two_dim

array([[  0,  10,  20],
       [  5,  15,  25],
       [100, 200, 300]])

In [ ]:
two_dim[0]

array([ 0, 10, 20])

In [ ]:
two_dim[1][0]

5

In [ ]:
two_dim[1:3,:2]

array([[  5,  15],
       [100, 200]])

In [ ]:
two_dim[1:3,:1]

array([[  5],
       [100]])

In [ ]:
two_dim[1:2,:2]

array([[ 5, 15]])

In [ ]:
two_dim[1,:2]

array([ 5, 15])

In [ ]:
two_dim[1:3,:4]

array([[  5,  15,  25],
       [100, 200, 300]])

In [ ]:
two_dim[1:5,:2]

array([[  5,  15],
       [100, 200]])

In [ ]:
two_dim[0:3,:2]

array([[  0,  10],
       [  5,  15],
       [100, 200]])

In [ ]:
two_dim[(0,1)]

10

In [ ]:
my_arr = np.arange(25).reshape(5,5)
my_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
my_arr[(0,1)]

1

In [ ]:
my_arr[(0,1),]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
my_arr[[0,1],[0,4]]

array([0, 9])

In [ ]:
vals = np.array([100,5,0])
select = np.random.randint(0,3,size=(4,3))
select

array([[1, 1, 1],
       [2, 2, 2],
       [0, 0, 1],
       [1, 0, 1]])

In [ ]:
vals[select]

array([[  5,   5,   5],
       [  0,   0,   0],
       [100, 100,   5],
       [  5, 100,   5]])

In [ ]:
vals[[1,0,2]]

array([  5, 100,   0])

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
slice_of_arr = arr[:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [ ]:
slice_of_arr[:] = 100
slice_of_arr

array([100, 100, 100, 100, 100])

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [ ]:
fancy_arr = np.arange(10)
fancy_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
fancy_index_arr = fancy_arr[np.arange(5)]
fancy_index_arr

array([0, 1, 2, 3, 4])

In [ ]:
fancy_index_arr[:] = 100
fancy_index_arr

array([100, 100, 100, 100, 100])

In [ ]:
fancy_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
slice_of_arr.base is None

False

In [ ]:
fancy_index_arr.base is None

True

In [ ]:
slice_of_arr.base is arr

True

In [ ]:
arr = np.arange(10)
print('arr')
print(arr)

slice_of_arr = arr[:5].copy()
print('slice_of_arr')
print(slice_of_arr)

slice_of_arr[:] = 100
print('slice_of_arr')
print(slice_of_arr)

print('arr')
print(arr)

arr
[0 1 2 3 4 5 6 7 8 9]
slice_of_arr
[0 1 2 3 4]
slice_of_arr
[100 100 100 100 100]
arr
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
slice_of_arr is arr

False

In [ ]:
macierz = np.arange(9).reshape(3, 3)
print(macierz)
macierz[-1, -1] = 999
macierz[1:, 1:] = 0
print('\n', macierz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

 [[0 1 2]
 [3 0 0]
 [6 0 0]]


In [ ]:
arr = np.arange(0,50,5)
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
arr>15

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[arr>15]

array([20, 25, 30, 35, 40, 45])

In [ ]:
(arr>15) & (arr!=40)

array([False, False, False, False,  True,  True,  True,  True, False,
        True])

In [ ]:
arr[(arr>15) & (arr!=40)]

array([20, 25, 30, 35, 45])

In [ ]:
arr[arr>15 & arr!=40]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
(arr<10) | (arr>=20)

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[(arr<10) | (arr>=20)]

array([ 0,  5, 20, 25, 30, 35, 40, 45])

In [ ]:
np.logical_or(arr<10,arr>=20)

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[np.logical_or(arr<10,arr>=20)]

array([ 0,  5, 20, 25, 30, 35, 40, 45])

In [ ]:
np.where(arr<=43)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),)