In [1]:
print("Hello World!")

Hello World!


In [2]:
import numpy as np
print(np.__version__)

1.26.4


In [3]:
exams = np.asarray([[100, 200, 50, 400], [50, 0, 0, 100], [350, 100, 50, 200]])
exams

array([[100, 200,  50, 400],
       [ 50,   0,   0, 100],
       [350, 100,  50, 200]])

In [4]:
u_a = [100,200,50,400]
u_b = [50,0,0,100]
u_c = [350,100,50,200]
exams = [u_a,u_b,u_c]

In [5]:
exams

[[100, 200, 50, 400], [50, 0, 0, 100], [350, 100, 50, 200]]

In [6]:
my_list = [i for i in range(1000000)]
my_array = np.arange(1000000)

In [7]:
%time for _ in range(10): my_list2 = [x**2 for x in my_list]

CPU times: user 615 ms, sys: 359 ms, total: 975 ms
Wall time: 1.09 s


In [8]:
%time for _ in range(10):my_array_2 = my_array **2

CPU times: user 15.1 ms, sys: 0 ns, total: 15.1 ms
Wall time: 18.4 ms


In [9]:
one_dim = np.array([1,2,3,4])
type(one_dim)

numpy.ndarray

In [10]:
one_dim.shape # kształt

(4,)

In [11]:
one_dim.ndim # liczba wymiarów – w tym przypadku 1 wymiar

1

In [12]:
one_dim_horizontal = np.array([[1,2,3,4]])
print(one_dim_horizontal.shape)
one_dim_horizontal

(1, 4)


array([[1, 2, 3, 4]])

In [13]:
one_dim_vertical = one_dim_horizontal.reshape(-1, 1)
one_dim_vertical

array([[1],
       [2],
       [3],
       [4]])

In [14]:
one_dim_vertical.reshape(1, -1)

array([[1, 2, 3, 4]])

In [15]:
two_dim = np.array([[100, 200, 50, 400], [50, 0, 0, 100], [350, 100, 50, 200]])

print("len: " + str(len(two_dim)))
print("shape: " + str(two_dim.shape))
print("ndim: " + str(two_dim.ndim))

len: 3
shape: (3, 4)
ndim: 2


In [16]:
two_dim.size

12

In [17]:
two_dim.itemsize

8

In [18]:
one_dim.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [20]:
two_dim

array([[100, 200,  50, 400],
       [ 50,   0,   0, 100],
       [350, 100,  50, 200]])

In [21]:
two_dim.reshape(4,3)

array([[100, 200,  50],
       [400,  50,   0],
       [  0, 100, 350],
       [100,  50, 200]])

In [22]:
two_dim.reshape(4,4)

ValueError: cannot reshape array of size 12 into shape (4,4)

In [23]:
two_dim.flatten()

array([100, 200,  50, 400,  50,   0,   0, 100, 350, 100,  50, 200])

In [24]:
my_list = [1,2,3,4,5]
np.array(my_list)

array([1, 2, 3, 4, 5])

In [25]:
my_nested_list = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_nested_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
np.zeros(3)

array([0., 0., 0.])

In [29]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [31]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.ones((2,3),dtype=np.int8)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [33]:
arr_01 = np.array([5, 10, 20])
print(arr_01, arr_01.dtype)
arr_02 = np.array([5, 10, 20.0])
print(arr_02, arr_02.dtype)
arr_03 = np.array([5, 10, '20'])
print(arr_03, arr_03.dtype)

[ 5 10 20] int64
[ 5. 10. 20.] float64
['5' '10' '20'] <U21


In [34]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [35]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
np.diag([5, 0, 4, 1, 3, 2])

array([[5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 2]])

In [37]:
np.random.rand(5)

array([0.42637763, 0.67849359, 0.44001084, 0.72001487, 0.24932508])

In [38]:
np.random.rand(5,5)

array([[0.25987061, 0.61634716, 0.04683939, 0.1764666 , 0.8971459 ],
       [0.83124557, 0.52330769, 0.02734878, 0.93395947, 0.65306162],
       [0.0590904 , 0.59142912, 0.75617678, 0.42760715, 0.95772818],
       [0.18172511, 0.45655965, 0.43015777, 0.9772176 , 0.0135689 ],
       [0.05045087, 0.18247199, 0.28224583, 0.49516454, 0.42952942]])

In [39]:
np.random.randint(1,100,10)

array([33, 29,  3, 60, 88, 81, 35, 30, 52, 82])