# Ćwiczenie
### Zadanie 1
Zwróć z macierzy arr wiersz o indeksie nr 2, lecz tylko dla tych kolumn, których suma przekracza 30.<br>

In [8]:
import numpy as np

# Tworzenie macierzy
arr = np.arange(20).reshape(4, 5)
print(arr)

# Obliczenie sumy każdej kolumny
column_sums = np.sum(arr, axis=0)

# Sprawdzenie, które kolumny mają sumę większą niż 30
columns_to_keep = column_sums > 30

# Wybranie wiersza o indeksie 2, ale tylko dla kolumn z sumą > 30
result = arr[2, columns_to_keep]

# alternatywnie arr[2, arr.sum(axis=0)>30]
print("Wiersz o indeksie 2 dla kolumn z sumą > 30:")
print(result)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Wiersz o indeksie 2 dla kolumn z sumą > 30:
[11 12 13 14]


### Zadanie 2
Mamy dane dwie tablice: a i b. Stwórz program filtrujący wartości z b, które korespondują z elementami a i są większe od 100 i mniejsze od 110.<br>
<prep>
a = np.array([97,101,105,111,117,125])<br>
b = np.array(['a','e','i','o','u','y'])<br>
</prep>

In [10]:
import numpy as np

# Dane wejściowe
a = np.array([97, 101, 105, 111, 117, 125])
b = np.array(['a', 'e', 'i', 'o', 'u', 'y'])

# Warunek: elementy z a większe niż 100 i mniejsze niż 110
condition = (a > 100) & (a < 110)

# Filtrowanie wartości z b na podstawie warunku
filtered_b = b[condition]

# alternatywnie filtered_b = b[(a > 100) & (a < 110)]
print("Przefiltrowane wartości z b:")
print(filtered_b)

Przefiltrowane wartości z b:
['e' 'i']


### Zadanie 3
Stwórz program, który ze wskazanej macierzy wyciągnie odpowiednio najmniejszą i największą wartość dla każdego wiersza.<br>
<prep>
[[0 4 1]<br>
[2 0 4]]<br>
</prep>

In [12]:
import numpy as np

# Tworzenie macierzy
matrix = np.array([[0, 4, 1],
                   [2, 0, 4]])

# Znajdowanie najmniejszych wartości dla każdego wiersza
min_values = np.min(matrix, axis=1)

# Znajdowanie największych wartości dla każdego wiersza
max_values = np.max(matrix, axis=1)

print("Najmniejsze wartości dla każdego wiersza:")
print(min_values)

print("\nNajwiększe wartości dla każdego wiersza:")
print(max_values)

Najmniejsze wartości dla każdego wiersza:
[0 0]

Największe wartości dla każdego wiersza:
[4 4]


### Zadanie 4
Mając tablicę np.arange(11), odwróć znak wszystkich elementów większych od 3 i mniejszych od 8.<br>

In [13]:
import numpy as np

# Tworzenie tablicy
arr = np.arange(11)

# Warunek: elementy większe niż 3 i mniejsze niż 8
condition = (arr > 3) & (arr < 8)

# Odwrócenie znaku elementów spełniających warunek
arr[condition] = -arr[condition]

print("Tablica po odwróceniu znaków:")
print(arr)

Tablica po odwróceniu znaków:
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
